=== raulgodii/JSON_XML_XPATH_XSL-FO_XSLT_exercises/XML/Relacion 2/ej11.dtd
<!ELEMENT Amuebla_SA (sucursal*)>

<!ELEMENT sucursal (pedido+)>

<!ELEMENT pedido (codigo_pedido, trabajador, fecha, observaciones_pedido?, plazo_revision, articulo*)>
<!ELEMENT codigo_pedido (#PCDATA)>
<!ELEMENT trabajador (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT observaciones_pedido (#PCDATA)>
<!ELEMENT plazo_revision (#PCDATA)>

<!ELEMENT articulo (codigo_articulo, unidades, precio, observaciones_articulo?)>
<!ELEMENT codigo_articulo (#PCDATA)>
<!ELEMENT unidades (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT observaciones_articulo (#PCDATA)>

<!ATTLIST Amuebla_SA sede CDATA "Madrid">
<!ATTLIST sucursal direccion1 CDATA #REQUIRED>
<!ATTLIST sucursal direccion2 CDATA #IMPLIED>
<!ATTLIST observaciones_pedido estado (urgente | incompleto) "incompleto">

=== raulgodii/JSON_XML_XPATH_XSL-FO_XSLT_exercises/XML/Relacion 2/ej11.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE Amuebla_SA SYSTEM "ej11.dtd">

<Amuebla_SA sede="Madrid">
    <sucursal direccion1="direccion" direccion2="direccion">
        <pedido>
            <codigo_pedido>PED001</codigo_pedido>
            <trabajador>Juan Pérez</trabajador>
            <fecha>2023-04-11</fecha>
            <observaciones_pedido estado="incompleto">sin observaciones</observaciones_pedido>
            <plazo_revision>10-15 días</plazo_revision>

            <articulo>
              <codigo_articulo>ABC-001</codigo_articulo>
              <unidades>2</unidades>
              <precio>100.00</precio>
              <observaciones_articulo>sin observaciones</observaciones_articulo>
            </articulo>
        </pedido>
    </sucursal>
</Amuebla_SA>
