=== raulgodii/JSON_XML_XPATH_XSL-FO_XSLT_exercises/XML/Relacion 2/ej16.dtd
<!ELEMENT cancion (titulo, compositores, productores, sello, artista)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT compositores (compositor+)>
<!ELEMENT productores (productor+)>
<!ELEMENT sello (#PCDATA)>
<!ELEMENT artista (#PCDATA)>

<!ELEMENT compositor (nombres_c, apellidos_c)>
<!ELEMENT nombres_c (#PCDATA)>
<!ELEMENT apellidos_c (#PCDATA)>

<!ELEMENT productor (nombres_p, apellidos_p)>
<!ELEMENT nombres_p (#PCDATA)>
<!ELEMENT apellidos_p (#PCDATA)>

<!ATTLIST cancion duracion CDATA #REQUIRED>
<!ATTLIST cancion anio CDATA #REQUIRED>

=== raulgodii/JSON_XML_XPATH_XSL-FO_XSLT_exercises/XML/Relacion 2/ej16.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE cancion SYSTEM "ej16.dtd">

<cancion duracion="4:47" anio="2008">
    <titulo>Give it 2 me</titulo>
    <compositores>
        <compositor>
            <nombres_c>Pharrel</nombres_c>
            <apellidos_c>Williams</apellidos_c>
        </compositor>
    </compositores>
    <productores>
        <productor>
            <nombres_p>Pharrel</nombres_p>
            <apellidos_p>_cWilliams</apellidos_p>
        </productor>
    </productores>
    <sello>Warner Bros. Records</sello>
    <artista>Madonna</artista>
</cancion>
